---
- name: creating rsa key
  openssh_keypair:
    path: /root/.ssh/id_rsa
    force: True

- name: copying keygen to master nodes
  command: sshpass -f /root/parthik/inventory/password.txt ssh-copy-id parthik@137.135.65.95 -o StrictHostKeyChecking=no


- name: copying keygen to ha-master nodes
  command: sshpass -f /root/parthik/inventory/password.txt ssh-copy-id parthik@40.121.33.137 -o StrictHostKeyChecking=no



- name: copying keygen to worker nodes
  command: sshpass -f /root/parthik/inventory/password.txt ssh-copy-id parthik@23.101.132.112 -o StrictHostKeyChecking=no

